name: Bundle and Publish Extension
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
        
    - name: Build with webpack
      run: npm run build
        
    - name: Create ZIP file
      run: |
        cd dist
        zip -r ../extension.zip .
        
    - name: Upload & release
      uses: mnao305/chrome-extension-upload@v5.0.0
      with:
        file-path: extension.zip
        extension-id: ${{ secrets.GOOGLE_WEBSTORE_EXTENSION_ID }}
        client-id: ${{ secrets.GOOGLE_WEBSTORE_CLIENT_ID }}
        client-secret: ${{ secrets.GOOGLE_WEBSTORE_CLIENT_SECRET }}
        refresh-token: ${{ secrets.GOOGLE_WEBSTORE_REFRESH_TOKEN }}
