name: Bundle and Publish Extension
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'CLAUDE.md'
      - 'README.md'
      - 'coverage/**'
      - '*.md'
      - '.vscode/**'
      - '.idea/**'
      - 'docs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: npm test
    
    - name: Bump patch version
      id: version
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        npm run version:patch
        NEW_VERSION=$(node -p "require('./package.json').version")
        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
        git add package.json public/manifest.json package-lock.json
        git commit -m "Bump version to $NEW_VERSION"
        git push origin main
    
    - name: Build with webpack
      run: npm run build
        
    - name: Create ZIP file
      run: |
        cd dist
        zip -r ../extension.zip .
        
    - name: Create and push tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag v${{ steps.version.outputs.version }}
        git push origin v${{ steps.version.outputs.version }}
        
    - name: Upload & release
      uses: mnao305/chrome-extension-upload@v5.0.0
      with:
        file-path: extension.zip
        extension-id: ${{ secrets.GOOGLE_WEBSTORE_EXTENSION_ID }}
        client-id: ${{ secrets.GOOGLE_WEBSTORE_CLIENT_ID }}
        client-secret: ${{ secrets.GOOGLE_WEBSTORE_CLIENT_SECRET }}
        refresh-token: ${{ secrets.GOOGLE_WEBSTORE_REFRESH_TOKEN }}
