name: Bundle and Publish Extension

on:
  workflow_dispatch:

jobs:
  build:
    name: Bundle and Publish Extension
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
        
    - name: Create ZIP file
      run: |
        cd "techne-extension Extension/"
        zip -r ../extension.zip Resources
        ls -la ../extension.zip
        
    - name: Upload & release
      uses: mnao305/chrome-extension-upload@v5.0.0
      with:
        file-path: extension.zip
        extension-id: ${{ secrets.GOOGLE_WEBSTORE_EXTENSION_ID }}
        client-id: ${{ secrets.GOOGLE_WEBSTORE_CLIENT_ID }}
        client-secret: ${{ secrets.GOOGLE_WEBSTORE_CLIENT_SECRET }}
        refresh-token: ${{ secrets.GOOGLE_WEBSTORE_REFRESH_TOKEN }}